export enum EntityType {

  // Geography
  CONTINENT = "continent",
  REGION = "region",
  COUNTRY = "country",
  TERRITORY = "territory",
  STATE = "state",
  PROVINCE = "province",
  DISTRICT = "district",
  LOCAL_GOVERNMENT = "local_government",
  CITY = "city",
  TOWN = "town",
  VILLAGE = "village",

  // Peoples & Identity
  PERSON = "person",
  ETHNIC_GROUP = "ethnic_group",
  TRIBE = "tribe",
  CLAN = "clan",
  DYNASTY = "dynasty",
  ROYAL_HOUSE = "royal_house",
  CIVILIZATION = "civilization",
  CULTURE = "culture",
  DIASPORA_COMMUNITY = "diaspora_community",

  // Governance
  EMPIRE = "empire",
  KINGDOM = "kingdom",
MONARCHY_SYSTEM = "monarchy_system",
CONSTITUTIONAL_MONARCHY = "constitutional_monarchy",
FEDERAL_SYSTEM = "federal_system",
UNITARY_SYSTEM = "unitary_system",
CONFEDERATION_SYSTEM = "confederation_system",
PARLIAMENTARY_SYSTEM = "parliamentary_system",
PRESIDENTIAL_SYSTEM = "presidential_system",
THEOCRACY = "theocracy",
TRADITIONAL_GOVERNANCE = "traditional_governance",
MILITARY_GOVERNMENT = "military_government",
  REPUBLIC = "republic",
  GOVERNMENT = "government",
  POLITICAL_PARTY = "political_party",
  MINISTRY = "ministry",
  TRADITIONAL_INSTITUTION = "traditional_institution",
  MILITARY_UNIT = "military_unit",

  // Language & Belief
  LANGUAGE = "language",
  LANGUAGE_FAMILY = "language_family",
  RELIGION = "religion",
  BELIEF_SYSTEM = "belief_system",
  DEITY = "deity",
  SPIRIT = "spirit",
  MYTHOLOGY = "mythology",

  // Culture
  FESTIVAL = "festival",
CARNIVAL = "carnival",
RITE_OF_PASSAGE = "rite_of_passage",
INITIATION_RITE = "initiation_rite",
NAMING_CEREMONY = "naming_ceremony",
WEDDING_TRADITION = "wedding_tradition",
FUNERARY_RITE = "funerary_rite",
CORONATION_CEREMONY = "coronation_ceremony",
MYTH = "myth",
RIDDLE = "riddle",
EPIC_POEM = "epic_poem",
TEXTILE_TRADITION = "textile_tradition",
FABRIC_TYPE = "fabric_type",
DYEING_TECHNIQUE = "dyeing_technique",
TRADITIONAL_GARMENT = "traditional_garment",
HEADDRESS = "headdress",
CROWN = "crown",
  CEREMONY = "ceremony",
  CUSTOM = "custom",
  RITUAL = "ritual",
  PROVERB = "proverb",
  LEGEND = "legend",
  FOLKTALE = "folktale",
  ORAL_TRADITION = "oral_tradition",

  // Arts
  ARTWORK = "artwork",
  ART_STYLE = "art_style",
  PAINTING = "painting",
  SCULPTURE = "sculpture",
  MASK = "mask",
  TEXTILE = "textile",
  CLOTHING = "clothing",

  MUSIC_GENRE = "music_genre",
  SONG = "song",
  DANCE = "dance",
  MUSICAL_INSTRUMENT = "musical_instrument",

  FILM = "film",
  BOOK = "book",
  MANUSCRIPT = "manuscript",
  DOCUMENT = "document",

  // Architecture
  PALACE = "palace",
  MONUMENT = "monument",
  LANDMARK = "landmark",
  ARCHAEOLOGICAL_SITE = "archaeological_site",
  SACRED_SITE = "sacred_site",
  ARCHITECTURAL_STYLE = "architectural_style",

  // Education
  UNIVERSITY = "university",
  SCHOOL = "school",
  LIBRARY = "library",
  RESEARCH_CENTER = "research_center",

  // Health
  HOSPITAL = "hospital",
  DISEASE = "disease",
  PANDEMIC = "pandemic",

  // Environment
  RIVER = "river",
  LAKE = "lake",
  MOUNTAIN = "mountain",
  FOREST = "forest",
  DESERT = "desert",
  ISLAND = "island",
  ECOZONE = "ecozone",
  CLIMATE_ZONE = "climate_zone",
  FLORA = "flora",
  FAUNA = "fauna",
  NATURAL_RESOURCE = "natural_resource",

  // Economy
  CURRENCY = "currency",
  COMMODITY = "commodity",
  INDUSTRY = "industry",
  MARKET = "market",
  COMPANY = "company",
  TRADE_ROUTE = "trade_route",

  // Infrastructure
  ROAD = "road",
  RAILWAY = "railway",
  BRIDGE = "bridge",
  AIRPORT = "airport",
  SEAPORT = "seaport",
  DAM = "dam",

  // History
  HISTORICAL_EVENT = "historical_event",
PREHISTORIC_ERA = "prehistoric_era",
STONE_AGE = "stone_age",
IRON_AGE = "iron_age",
PRE_COLONIAL_ERA = "pre_colonial_era",
COLONIAL_ERA = "colonial_era",
POST_COLONIAL_ERA = "post_colonial_era",
INDEPENDENCE_ERA = "independence_era",
CIVIL_WAR = "civil_war",
SIEGE = "siege",
REBELLION = "rebellion",
COUP = "coup",
PEACE_AGREEMENT = "peace_agreement",
POLITICAL_CONFERENCE = "political_conference",
EXPEDITION = "expedition",
LIBERATION_MOVEMENT = "liberation_movement",
INDEPENDENCE_MOVEMENT = "independence_movement",
RUIN = "ruin",
ARTIFACT = "artifact",
MEGALITHIC_SITE = "megalithic_site",
ROCK_ART_SITE = "rock_art_site",
FOSSIL_SITE = "fossil_site",
  BATTLE = "battle",
  WAR = "war",
  MIGRATION = "migration",
  CORONATION = "coronation",
  REVOLUTION = "revolution",
  ELECTION = "election",

  // Law
  TREATY = "treaty",
  CONSTITUTION = "constitution",
  LEGAL_CODE = "legal_code",

  // Technology
  TECHNOLOGY = "technology",
  INVENTION = "invention",
  TECH_HUB = "tech_hub"
}